"""
Генератор terms.json. Запускать из корня проекта:
  python scripts/generate_terms.py
Каждый батч добавляет термины в data/terms.json.
"""
import json
import os

OUTPUT = os.path.join(os.path.dirname(__file__), "..", "data", "terms.json")


def load_existing() -> list:
    if os.path.exists(OUTPUT):
        with open(OUTPUT, "r", encoding="utf-8") as f:
            return json.load(f)
    return []


def save(terms: list):
    os.makedirs(os.path.dirname(OUTPUT), exist_ok=True)
    with open(OUTPUT, "w", encoding="utf-8") as f:
        json.dump(terms, f, ensure_ascii=False, indent=2)
    print(f"Сохранено терминов: {len(terms)}")


BATCH_1 = [
    {"term_eng": "Offer", "term_rus": "Оферта", "category": "Contract Law",
     "definition": "A proposal to enter into a contract on specific terms.",
     "example": "The seller made an offer to sell the car for $10,000."},
    {"term_eng": "Acceptance", "term_rus": "Акцепт", "category": "Contract Law",
     "definition": "An unqualified agreement to the terms of an offer.",
     "example": "The buyer's acceptance of the offer formed a binding contract."},
    {"term_eng": "Consideration", "term_rus": "Встречное предоставление", "category": "Contract Law",
     "definition": "Something of value exchanged between parties to make a contract enforceable.",
     "example": "The consideration for the agreement was $500 paid upon signing."},
    {"term_eng": "Breach of contract", "term_rus": "Нарушение договора", "category": "Contract Law",
     "definition": "Failure to perform any term of a contract without a legitimate excuse.",
     "example": "The contractor's failure to deliver on time constituted a breach of contract."},
    {"term_eng": "Damages", "term_rus": "Убытки", "category": "Contract Law",
     "definition": "A monetary award to compensate for loss caused by breach of contract.",
     "example": "The court awarded damages of $50,000 for the breach of the supply agreement."},
    {"term_eng": "Termination", "term_rus": "Расторжение", "category": "Contract Law",
     "definition": "The ending of a contract by one or both parties.",
     "example": "The client exercised the right of termination after repeated delays."},
    {"term_eng": "Warranty", "term_rus": "Гарантия", "category": "Contract Law",
     "definition": "A promise that certain facts or conditions are true or will happen.",
     "example": "The seller gave a warranty that the goods were free from defects."},
    {"term_eng": "Indemnification", "term_rus": "Возмещение убытков", "category": "Contract Law",
     "definition": "An obligation to compensate another party for losses or damages.",
     "example": "The indemnification clause required the vendor to cover all third-party claims."},
    {"term_eng": "Novation", "term_rus": "Новация", "category": "Contract Law",
     "definition": "Substitution of a new contract or party for an old one.",
     "example": "By novation, the original debtor was replaced by a new obligor."},
    {"term_eng": "Assignment", "term_rus": "Уступка прав", "category": "Contract Law",
     "definition": "Transfer of rights or obligations under a contract to a third party.",
     "example": "The contractor assigned its payment rights to a financing company."},
    {"term_eng": "Subrogation", "term_rus": "Суброгация", "category": "Contract Law",
     "definition": "The substitution of one party for another in a legal right or claim.",
     "example": "The insurer exercised subrogation rights against the negligent driver."},
    {"term_eng": "Specific performance", "term_rus": "Исполнение в натуре", "category": "Contract Law",
     "definition": "A court order requiring a party to perform its contractual obligations.",
     "example": "The court ordered specific performance because the property was unique."},
    {"term_eng": "Liquidated damages", "term_rus": "Заранее оценённые убытки", "category": "Contract Law",
     "definition": "A pre-agreed sum payable upon breach, set out in the contract.",
     "example": "The contract provided liquidated damages of $1,000 per day of delay."},
    {"term_eng": "Force majeure", "term_rus": "Форс-мажор", "category": "Contract Law",
     "definition": "An unforeseeable event that prevents a party from fulfilling its obligations.",
     "example": "The pandemic was invoked as force majeure to excuse non-performance."},
    {"term_eng": "Material breach", "term_rus": "Существенное нарушение", "category": "Contract Law",
     "definition": "A breach significant enough to excuse the other party from performance.",
     "example": "Delivering counterfeit goods was held to be a material breach."},
    {"term_eng": "Anticipatory breach", "term_rus": "Предвидимое нарушение", "category": "Contract Law",
     "definition": "A declaration before performance is due that a party will not perform.",
     "example": "His statement that he would not deliver constituted an anticipatory breach."},
    {"term_eng": "Rescission", "term_rus": "Расторжение договора (аннулирование)", "category": "Contract Law",
     "definition": "Cancellation of a contract so that parties are restored to their original positions.",
     "example": "The court granted rescission due to fraudulent misrepresentation."},
    {"term_eng": "Restitution", "term_rus": "Реституция", "category": "Contract Law",
     "definition": "Restoration of a benefit conferred on a party to prevent unjust enrichment.",
     "example": "She sought restitution of the advance payment after the contract was voided."},
    {"term_eng": "Quantum meruit", "term_rus": "Квантум мерит (оплата по факту)", "category": "Contract Law",
     "definition": "A claim for reasonable payment for services rendered in the absence of a contract.",
     "example": "The contractor claimed quantum meruit for work done before the contract was signed."},
    {"term_eng": "Unjust enrichment", "term_rus": "Неосновательное обогащение", "category": "Contract Law",
     "definition": "A gain obtained at another's expense without legal justification.",
     "example": "The court found unjust enrichment and ordered repayment of the sum."},
    {"term_eng": "Promissory estoppel", "term_rus": "Эстоппель на основе обещания", "category": "Contract Law",
     "definition": "A doctrine preventing a party from going back on a promise relied upon by another.",
     "example": "Promissory estoppel prevented the landlord from withdrawing the rent reduction."},
    {"term_eng": "Parol evidence rule", "term_rus": "Правило устных доказательств", "category": "Contract Law",
     "definition": "A rule limiting extrinsic evidence to vary a written contract.",
     "example": "Under the parol evidence rule, oral negotiations could not alter the written agreement."},
    {"term_eng": "Statute of Frauds", "term_rus": "Закон о мошенничестве (требование письменной формы)", "category": "Contract Law",
     "definition": "A law requiring certain contracts to be in writing to be enforceable.",
     "example": "The contract for the sale of land was unenforceable under the Statute of Frauds."},
    {"term_eng": "Capacity", "term_rus": "Дееспособность", "category": "Contract Law",
     "definition": "The legal ability of a party to enter into a binding contract.",
     "example": "A minor lacks capacity to enter into most contracts."},
    {"term_eng": "Duress", "term_rus": "Принуждение", "category": "Contract Law",
     "definition": "Unlawful pressure that causes a party to enter a contract against their will.",
     "example": "The agreement was voidable because it was signed under duress."},
    {"term_eng": "Undue influence", "term_rus": "Злоупотребление влиянием", "category": "Contract Law",
     "definition": "Improper pressure exploiting a relationship to influence a party's decision.",
     "example": "The elderly client signed under undue influence of her financial adviser."},
    {"term_eng": "Misrepresentation", "term_rus": "Введение в заблуждение", "category": "Contract Law",
     "definition": "A false statement of fact that induces another party to enter a contract.",
     "example": "The buyer rescinded the contract due to the seller's misrepresentation about defects."},
    {"term_eng": "Impossibility", "term_rus": "Невозможность исполнения", "category": "Contract Law",
     "definition": "A doctrine excusing performance when it becomes objectively impossible.",
     "example": "Destruction of the subject matter created impossibility of performance."},
    {"term_eng": "Frustration of purpose", "term_rus": "Тщетность договора", "category": "Contract Law",
     "definition": "A doctrine excusing performance when the contract's purpose is destroyed.",
     "example": "Cancellation of the coronation frustrated the purpose of the room hire contract."},
    {"term_eng": "Condition precedent", "term_rus": "Отлагательное условие", "category": "Contract Law",
     "definition": "An event that must occur before a contractual obligation becomes due.",
     "example": "Obtaining planning permission was a condition precedent to the purchase."},
    {"term_eng": "Condition subsequent", "term_rus": "Отменительное условие", "category": "Contract Law",
     "definition": "An event whose occurrence ends an existing contractual obligation.",
     "example": "Loss of the license was a condition subsequent that terminated the agreement."},
    {"term_eng": "Indemnity clause", "term_rus": "Оговорка об освобождении от ответственности", "category": "Contract Law",
     "definition": "A contractual provision requiring one party to cover the other's losses.",
     "example": "The indemnity clause protected the client from supplier negligence claims."},
    {"term_eng": "Limitation of liability", "term_rus": "Ограничение ответственности", "category": "Contract Law",
     "definition": "A clause capping the amount recoverable from one party.",
     "example": "The limitation of liability clause set the maximum at the contract price."},
    {"term_eng": "Entire agreement clause", "term_rus": "Оговорка о полноте договора", "category": "Contract Law",
     "definition": "A clause stating the contract represents the parties' full agreement.",
     "example": "The entire agreement clause excluded all prior representations and warranties."},
    {"term_eng": "Severability", "term_rus": "Делимость (договора)", "category": "Contract Law",
     "definition": "A provision allowing the rest of a contract to stand if one part is invalid.",
     "example": "The severability clause ensured the contract remained valid despite the voided term."},
    {"term_eng": "Waiver", "term_rus": "Отказ от права", "category": "Contract Law",
     "definition": "Voluntary relinquishment of a known right.",
     "example": "By accepting the late payment, the creditor waived the right to charge penalties."},
    {"term_eng": "Non-compete clause", "term_rus": "Оговорка о запрете конкуренции", "category": "Contract Law",
     "definition": "A clause preventing a party from engaging in competing business activities.",
     "example": "The non-compete clause prohibited the employee from joining a rival for two years."},
    {"term_eng": "Non-disclosure agreement", "term_rus": "Соглашение о неразглашении", "category": "Contract Law",
     "definition": "A contract obligating parties to keep specified information confidential.",
     "example": "The parties signed a non-disclosure agreement before sharing financial data."},
    {"term_eng": "Governing law", "term_rus": "Применимое право", "category": "Contract Law",
     "definition": "The jurisdiction's law that applies to interpret and enforce a contract.",
     "example": "The governing law clause specified that English law would apply."},
    {"term_eng": "Arbitration clause", "term_rus": "Арбитражная оговорка", "category": "Contract Law",
     "definition": "A provision requiring disputes to be resolved by arbitration.",
     "example": "Under the arbitration clause, disputes were referred to ICC arbitration."},
    {"term_eng": "Letter of intent", "term_rus": "Письмо о намерениях", "category": "Contract Law",
     "definition": "A document expressing the intent to enter into a future agreement.",
     "example": "The parties signed a letter of intent pending completion of due diligence."},
    {"term_eng": "Memorandum of understanding", "term_rus": "Меморандум о взаимопонимании", "category": "Contract Law",
     "definition": "A non-binding agreement outlining the terms of a future contract.",
     "example": "The memorandum of understanding set out the framework for the joint venture."},
    {"term_eng": "Due diligence", "term_rus": "Надлежащая проверка", "category": "Contract Law",
     "definition": "Investigation of a business or asset before signing a binding agreement.",
     "example": "The buyer conducted full due diligence before signing the acquisition agreement."},
    {"term_eng": "Earnout", "term_rus": "Отложенное вознаграждение", "category": "Contract Law",
     "definition": "Additional purchase price contingent on the target meeting future milestones.",
     "example": "The earnout provision linked $2 million of the price to revenue targets."},
    {"term_eng": "Escrow", "term_rus": "Эскроу", "category": "Contract Law",
     "definition": "A third-party arrangement holding assets until conditions are met.",
     "example": "The deposit was held in escrow until completion of the transaction."},
    {"term_eng": "Right of first refusal", "term_rus": "Преимущественное право покупки", "category": "Contract Law",
     "definition": "The right to match any offer received from a third party before the asset is sold.",
     "example": "The shareholder's right of first refusal prevented external parties from buying in."},
    {"term_eng": "Representations and warranties", "term_rus": "Заверения и гарантии", "category": "Contract Law",
     "definition": "Statements of fact and promises made to induce a party to enter a contract.",
     "example": "The seller's representations and warranties covered title and absence of liens."},
    {"term_eng": "Closing", "term_rus": "Закрытие сделки", "category": "Contract Law",
     "definition": "The final step of a transaction when documents are signed and funds transferred.",
     "example": "Closing took place on 1 March after all conditions precedent were satisfied."},
    {"term_eng": "Holdback", "term_rus": "Удержание части цены", "category": "Contract Law",
     "definition": "A portion of the purchase price retained to cover potential warranty claims.",
     "example": "A 10% holdback was retained for 18 months to secure indemnity obligations."},
    {"term_eng": "No-shop clause", "term_rus": "Оговорка об эксклюзивности переговоров", "category": "Contract Law",
     "definition": "A provision preventing a seller from soliciting other offers during negotiations.",
     "example": "The no-shop clause prevented the target from approaching other buyers for 60 days."},
    {"term_eng": "Counterparts", "term_rus": "Экземпляры договора", "category": "Contract Law",
     "definition": "Identical copies of a contract signed by different parties.",
     "example": "The agreement was signed in counterparts, each being an original."},
    {"term_eng": "Good faith", "term_rus": "Добросовестность", "category": "Contract Law",
     "definition": "An obligation to act honestly and fairly in performing a contract.",
     "example": "The parties were required to negotiate the renewal terms in good faith."},
    {"term_eng": "Best efforts", "term_rus": "Наилучшие усилия", "category": "Contract Law",
     "definition": "The highest standard of effort obligating a party to do all it reasonably can.",
     "example": "The agent was required to use best efforts to secure a buyer."},
    {"term_eng": "Reasonable efforts", "term_rus": "Разумные усилия", "category": "Contract Law",
     "definition": "A standard requiring a party to take steps that are reasonable in the circumstances.",
     "example": "The licensee undertook to use reasonable efforts to commercialise the product."},
    {"term_eng": "Time is of the essence", "term_rus": "Срок является существенным условием", "category": "Contract Law",
     "definition": "A clause making deadlines strict, so late performance is a material breach.",
     "example": "Because time was of the essence, the two-day delay justified termination."},
    {"term_eng": "Void contract", "term_rus": "Ничтожный договор", "category": "Contract Law",
     "definition": "A contract that has no legal effect from the beginning.",
     "example": "A contract for an illegal purpose is void and unenforceable."},
    {"term_eng": "Voidable contract", "term_rus": "Оспоримый договор", "category": "Contract Law",
     "definition": "A contract valid until one party elects to rescind it.",
     "example": "The contract was voidable at the option of the minor."},
    {"term_eng": "Adhesion contract", "term_rus": "Договор присоединения", "category": "Contract Law",
     "definition": "A standard-form contract offered on a take-it-or-leave-it basis.",
     "example": "The consumer challenged the adhesion contract's arbitration clause."},
    {"term_eng": "Unconscionability", "term_rus": "Кабальность условий", "category": "Contract Law",
     "definition": "A doctrine voiding contracts with oppressively unfair terms.",
     "example": "The court refused to enforce the clause on grounds of unconscionability."},
    {"term_eng": "Third-party beneficiary", "term_rus": "Третье лицо — выгодоприобретатель", "category": "Contract Law",
     "definition": "A person who is not a party to a contract but is intended to benefit from it.",
     "example": "The employee was a third-party beneficiary of the insurance policy."},
    {"term_eng": "Privity of contract", "term_rus": "Относительность договора", "category": "Contract Law",
     "definition": "The principle that only parties to a contract can sue or be sued under it.",
     "example": "The subcontractor could not sue the employer due to lack of privity of contract."},
    {"term_eng": "Bilateral contract", "term_rus": "Двусторонний договор", "category": "Contract Law",
     "definition": "A contract where both parties exchange mutual promises.",
     "example": "A sale of goods is a classic bilateral contract: goods for money."},
    {"term_eng": "Unilateral contract", "term_rus": "Односторонний договор", "category": "Contract Law",
     "definition": "A contract where one party makes a promise in exchange for an act.",
     "example": "The reward notice was a unilateral contract accepted by finding the lost dog."},
    {"term_eng": "Performance bond", "term_rus": "Гарантия исполнения обязательств", "category": "Contract Law",
     "definition": "A surety bond ensuring a contractor completes a project.",
     "example": "The employer called on the performance bond when the builder abandoned the site."},
    {"term_eng": "Letter of credit", "term_rus": "Аккредитив", "category": "Contract Law",
     "definition": "A bank's commitment to pay a seller upon presentation of specified documents.",
     "example": "Payment was secured by an irrevocable letter of credit issued by the buyer's bank."},
    {"term_eng": "Surety", "term_rus": "Поручитель", "category": "Contract Law",
     "definition": "A party that guarantees another's performance of an obligation.",
     "example": "The parent company acted as surety for its subsidiary's lease obligations."},
    {"term_eng": "Penalty clause", "term_rus": "Штрафная оговорка", "category": "Contract Law",
     "definition": "A clause imposing a deterrent payment that may be unenforceable if penal.",
     "example": "The court held the clause was a penalty, not liquidated damages, and struck it out."},
    {"term_eng": "Set-off", "term_rus": "Зачёт встречных требований", "category": "Contract Law",
     "definition": "A debtor's right to reduce a claim by an amount the creditor owes them.",
     "example": "The buyer exercised set-off, deducting repair costs from the purchase price."},
    {"term_eng": "Netting", "term_rus": "Неттинг", "category": "Contract Law",
     "definition": "Combining multiple obligations to produce a single net amount payable.",
     "example": "The ISDA master agreement provided for close-out netting on default."},
    {"term_eng": "Cross-default", "term_rus": "Перекрёстный дефолт", "category": "Contract Law",
     "definition": "A clause making default on one agreement an event of default on another.",
     "example": "The cross-default clause triggered acceleration on all facilities."},
    {"term_eng": "Acceleration clause", "term_rus": "Оговорка об ускорении", "category": "Contract Law",
     "definition": "A provision making a debt immediately payable upon occurrence of a default event.",
     "example": "Following the borrower's insolvency, the acceleration clause was invoked."},
    {"term_eng": "Injunction", "term_rus": "Судебный запрет", "category": "Contract Law",
     "definition": "A court order compelling or restraining a party from a specific action.",
     "example": "The court granted an injunction to stop the defendant from disclosing trade secrets."},
    {"term_eng": "Declaratory judgment", "term_rus": "Декларативное решение суда", "category": "Contract Law",
     "definition": "A court ruling clarifying the legal rights of parties without ordering any action.",
     "example": "The claimant sought a declaratory judgment that the clause was unenforceable."},
    {"term_eng": "Option agreement", "term_rus": "Опционный договор", "category": "Contract Law",
     "definition": "A contract giving one party the right to enter a transaction at a future date.",
     "example": "The option agreement gave the developer the right to buy the land within 12 months."},
    {"term_eng": "Drag-along rights", "term_rus": "Права принудительного выкупа", "category": "Contract Law",
     "definition": "Rights allowing a majority shareholder to force minorities to join a sale.",
     "example": "The drag-along rights allowed the 75% holder to compel sale to the acquirer."},
    {"term_eng": "Tag-along rights", "term_rus": "Права на совместную продажу", "category": "Contract Law",
     "definition": "Rights allowing minority shareholders to join a majority sale on the same terms.",
     "example": "Tag-along rights protected minority investors from being left behind in the exit."},
    {"term_eng": "Anti-dilution", "term_rus": "Антиразводнение", "category": "Contract Law",
     "definition": "A provision protecting an investor's ownership percentage from future issuances.",
     "example": "The anti-dilution clause adjusted the conversion price after the down round."},
    {"term_eng": "Vesting", "term_rus": "Вестинг", "category": "Contract Law",
     "definition": "The process by which rights to assets or shares accrue over time.",
     "example": "The founder's shares were subject to a four-year vesting schedule."},
    {"term_eng": "Cliff vesting", "term_rus": "Вестинг с отсрочкой", "category": "Contract Law",
     "definition": "A vesting arrangement where rights accrue all at once after a minimum period.",
     "example": "No shares vested before the one-year cliff under the employee incentive plan."},
    {"term_eng": "Change of control", "term_rus": "Смена контроля", "category": "Contract Law",
     "definition": "A transaction resulting in a new party acquiring control of a company.",
     "example": "The change of control clause allowed the counterparty to terminate on acquisition."},
    {"term_eng": "Earnest money", "term_rus": "Задаток", "category": "Contract Law",
     "definition": "A deposit paid to demonstrate seriousness of intent to complete a contract.",
     "example": "The buyer paid earnest money of $5,000 which would be forfeited on withdrawal."},
    {"term_eng": "Covenant", "term_rus": "Обязательство (ковенант)", "category": "Contract Law",
     "definition": "A contractual promise to do or refrain from doing something.",
     "example": "The borrower breached the financial covenant by exceeding the leverage ratio."},
    {"term_eng": "Representation", "term_rus": "Заверение", "category": "Contract Law",
     "definition": "A statement of present fact made to induce entry into a contract.",
     "example": "The seller's representation that accounts were accurate proved to be false."},
    {"term_eng": "Indemnity", "term_rus": "Индемнити", "category": "Contract Law",
     "definition": "A primary obligation to compensate another for specified losses.",
     "example": "The indemnity covered all costs arising from pre-completion tax liabilities."},
    {"term_eng": "Sub-licence", "term_rus": "Сублицензия", "category": "Contract Law",
     "definition": "A licence granted by a licensee to a third party.",
     "example": "The software licensee granted a sub-licence to its affiliated company."},
    {"term_eng": "Royalty", "term_rus": "Роялти", "category": "Contract Law",
     "definition": "A payment made for the use of intellectual property or natural resources.",
     "example": "The inventor received a 5% royalty on all sales under the licence agreement."},
    {"term_eng": "Milestone", "term_rus": "Этап (контракта)", "category": "Contract Law",
     "definition": "A specific event or deliverable triggering payment or other obligation.",
     "example": "Payment of $100,000 was due upon achievement of the first milestone."},
    {"term_eng": "Service level agreement", "term_rus": "Соглашение об уровне обслуживания", "category": "Contract Law",
     "definition": "A contract defining the standard of service a provider must deliver.",
     "example": "The SLA required 99.9% uptime with penalties for each hour of downtime."},
    {"term_eng": "Cure period", "term_rus": "Период устранения нарушения", "category": "Contract Law",
     "definition": "A specified time allowed to remedy a breach before the contract is terminated.",
     "example": "The defaulting party had a 30-day cure period to remedy the payment failure."},
    {"term_eng": "Termination for convenience", "term_rus": "Расторжение по усмотрению стороны", "category": "Contract Law",
     "definition": "The right to end a contract without cause on giving notice.",
     "example": "The client terminated for convenience, paying only the agreed wind-down costs."},
    {"term_eng": "Termination for cause", "term_rus": "Расторжение по основаниям", "category": "Contract Law",
     "definition": "Ending a contract because the other party has committed a specified breach.",
     "example": "Termination for cause was triggered by the supplier's insolvency."},
    {"term_eng": "Survival clause", "term_rus": "Оговорка о сохранении силы", "category": "Contract Law",
     "definition": "A provision keeping certain obligations in force after contract termination.",
     "example": "The survival clause kept confidentiality obligations alive for five years post-termination."},
    {"term_eng": "Counterparty", "term_rus": "Контрагент", "category": "Contract Law",
     "definition": "The other party to a contract or financial transaction.",
     "example": "The bank assessed the counterparty's creditworthiness before execution."},
    {"term_eng": "Executory contract", "term_rus": "Незавершённый договор", "category": "Contract Law",
     "definition": "A contract where obligations on both sides remain to be performed.",
     "example": "The trustee in bankruptcy chose to adopt the executory contract."},
    {"term_eng": "Unconscionable contract", "term_rus": "Кабальный договор", "category": "Contract Law",
     "definition": "A contract so one-sided or oppressive that a court may refuse to enforce it.",
     "example": "The court declined to enforce the unconscionable contract signed by an illiterate borrower."},
    {"term_eng": "Contractual capacity", "term_rus": "Договорная дееспособность", "category": "Contract Law",
     "definition": "The legal ability to enter into a binding contract.",
     "example": "Contractual capacity requires the party to be of legal age and sound mind."},
    {"term_eng": "Offer and acceptance", "term_rus": "Оферта и акцепт", "category": "Contract Law",
     "definition": "The two core elements forming a binding agreement.",
     "example": "Offer and acceptance were established by the exchange of signed term sheets."},
    {"term_eng": "Battle of the forms", "term_rus": "Битва форм", "category": "Contract Law",
     "definition": "A conflict arising when parties exchange contradictory standard terms.",
     "example": "The battle of the forms was resolved by applying the last shot rule."},
    {"term_eng": "Implied term", "term_rus": "Подразумеваемое условие", "category": "Contract Law",
     "definition": "A term not expressly stated but incorporated into a contract by law or custom.",
     "example": "An implied term of merchantability applied to the sale of goods."},
    {"term_eng": "Express term", "term_rus": "Явно выраженное условие", "category": "Contract Law",
     "definition": "A term explicitly agreed by the parties, whether orally or in writing.",
     "example": "The delivery date was an express term of the sale contract."},
]

if __name__ == "__main__":
    existing = load_existing()
    existing_keys = {t["term_eng"] for t in existing}
    new_terms = [t for t in BATCH_1 if t["term_eng"] not in existing_keys]
    all_terms = existing + new_terms
    save(all_terms)
    print(f"Добавлено новых: {len(new_terms)}, всего: {len(all_terms)}")
